FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
RUN apt-get update && apt-get install -y libgl1-mesa-glx libsm6 libxext6
COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt